"""
signals_db.py

Stores every trade card generated by the advisor into a local SQLite DB.
The FastAPI server reads from this same DB to serve the UI.
Both processes share the file — writes from advisor, reads from API.
"""
import json
import sqlite3
from contextlib import closing
from pathlib import Path

# Stored one level up so the FastAPI server can reach it at the project root
DB_PATH = Path(__file__).parent.parent / "signals.db"


def init_db():
    with closing(sqlite3.connect(str(DB_PATH))) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS signals (
                id                   INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at           DATETIME DEFAULT CURRENT_TIMESTAMP,
                channel              TEXT,
                symbol               TEXT,
                side                 TEXT,
                entry                REAL,
                sl                   REAL,
                sl_distance_pct      REAL,
                tp_levels            TEXT,
                rr_ratios            TEXT,
                leverage             INTEGER,
                quantity             REAL,
                position_size_usdt   REAL,
                margin_required_usdt REAL,
                risk_amount_usdt     REAL,
                risk_pct             REAL,
                balance_usdt         REAL,
                trade_card           TEXT,
                approved             INTEGER DEFAULT 1
            )
        """)
        conn.commit()


def save_signal(channel: str, sizing: dict, trade_card: str, approved: bool = True):
    init_db()
    with closing(sqlite3.connect(str(DB_PATH))) as conn:
        conn.execute("""
            INSERT INTO signals (
                channel, symbol, side, entry, sl, sl_distance_pct,
                tp_levels, rr_ratios, leverage, quantity,
                position_size_usdt, margin_required_usdt,
                risk_amount_usdt, risk_pct, balance_usdt,
                trade_card, approved
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (
            channel,
            sizing.get("symbol", ""),
            sizing.get("side", ""),
            sizing.get("entry", 0),
            sizing.get("sl", 0),
            sizing.get("sl_distance_pct", 0),
            json.dumps(sizing.get("tp_levels", [])),
            json.dumps(sizing.get("rr_ratios", [])),
            sizing.get("leverage", 0),
            sizing.get("quantity", 0),
            sizing.get("position_size_usdt", 0),
            sizing.get("margin_required_usdt", 0),
            sizing.get("risk_amount_usdt", 0),
            sizing.get("risk_pct", 0),
            sizing.get("balance_usdt", 0),
            trade_card,
            1 if approved else 0,
        ))
        conn.commit()
        return conn.execute("SELECT last_insert_rowid()").fetchone()[0]


def get_recent_signals(limit: int = 50, after_id: int = 0) -> list[dict]:
    init_db()
    with closing(sqlite3.connect(str(DB_PATH))) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM signals WHERE id > ? ORDER BY id DESC LIMIT ?",
            (after_id, limit)
        ).fetchall()
        result = []
        for r in rows:
            d = dict(r)
            d["tp_levels"] = json.loads(d["tp_levels"] or "[]")
            d["rr_ratios"] = json.loads(d["rr_ratios"] or "[]")
            result.append(d)
        return result
